### ISSUE TITLE
Occasionally the navigation menu is not augmented.

### ISSUE THREAD

**Issue by moonrockfamily** [EduShareGeorgian/portalResponsiveUi#19]
Missing chevron and expand/collapse feature.
Sibling menu items are showing.

![image](https://user-images.githubusercontent.com/1872992/31547982-4d555d42-aff7-11e7-9571-737778887ad2.png)

**Comment by moonrockfamily** [comment]
Repeated testing/reloading the page will occasionally manifest the misbehavior.

Debugging identified the PnPResponsiveApp.setUpToggling function getting invoked prior to the page content/DOM hence the element removal and augmentation with chevron/expand-collapse behavior targeted no dom elements!

**Comment by ThomasLamb** [comment]
closing old issue on stale project that can be archived
